//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public int IDALUMNO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOPATERNO { get; set; }
        public string APELLIDOMATERNO { get; set; }
        public string TELEFONO { get; set; }
        public string IMAGEN { get; set; }
        public string USER1 { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
