//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCUELA
    {
        public string CLAVESC { get; set; }
        public string IMAGEN { get; set; }
        public string DIRECCION { get; set; }
        public string VISION { get; set; }
        public string MISION { get; set; }
        public string HISTORIA { get; set; }
        public string USER1 { get; set; }
        public int ID_E { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
