//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PICTOCAMEntities1 : DbContext
    {
        public PICTOCAMEntities1()
            : base("name=PICTOCAMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNO> ALUMNO { get; set; }
        public virtual DbSet<ESCUELA> ESCUELA { get; set; }
        public virtual DbSet<GRUPO> GRUPO { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<NOTICIAS> NOTICIAS { get; set; }
        public virtual DbSet<PALABRA_IMAGEN> PALABRA_IMAGEN { get; set; }
        public virtual DbSet<PICTOGRAMA> PICTOGRAMA { get; set; }
        public virtual DbSet<TIPS> TIPS { get; set; }
        public virtual DbSet<TIPUSU> TIPUSU { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
