//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICTOGRAMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PICTOGRAMA()
        {
            this.PALABRA_IMAGEN = new HashSet<PALABRA_IMAGEN>();
            this.PICTOGRAMA1 = new HashSet<PICTOGRAMA>();
        }
    
        public decimal ID { get; set; }
        public string RUTA { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> REF { get; set; }
        public string USUARIO1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PALABRA_IMAGEN> PALABRA_IMAGEN { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PICTOGRAMA> PICTOGRAMA1 { get; set; }
        public virtual PICTOGRAMA PICTOGRAMA2 { get; set; }
    }
}
