//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPS
    {
        public decimal ID_T { get; set; }
        public string IMAGEN { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCION { get; set; }
        public string CONTENIDO { get; set; }
        public Nullable<System.TimeSpan> HORA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string USER1 { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
